Staff_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 用户信息
    url(r'^staff/', include('staff.urls', namespace='staff')),

    #用户操作
    url(r'^user_op/', include('user_operation.urls',namespace='user_op')),
]

staff/urls.py
from django.conf.urls import url

from staff import views

urlpatterns = [
    # 查看员工列表
    url(r'^staffList/', views.staffList, name='staffList'),

    # 删除员工
    url(r'^staff_delete/', views.staff_delete, name='staff_delete'),

    # 更新员工信息
    url(r'^staff_update/', views.staff_update, name='staff_update'),

    # 查看员工信息
    url(r'^staff_info/', views.staff_info, name='staff_info'),

    # 添加新员工
    url(r'add_staff/', views.add_staff, name='add_staff'),

    # 查询员工
    url(r'search_staff/', views.search_staff, name='search_staff'),

]

user_operation/urls.py
from django.conf.urls import url

from user_operation import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),

    # 注册
    url(r'^register/', views.register, name='register'),

    # 登出
    url(r'^logout/', views.logout, name='logout'),
]

templates/add_staff.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center">添加新员工</h1>
    <hr>

    {% if error == 0 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">员工信息不能为空！</div>
    {% endif %}
    {% if error == 1 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">年龄有误！</div>
    {% endif %}

    <form class="form-horizontal" action="{% url 'staff:add_staff' %}" method="POST" enctype="multipart/form-data">
        {#       名字#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">姓名</label>
            <div class="col-sm-4">
                <input type="text" name="name" class="form-control" id="account" placeholder="Name">
            </div>
        </div>

        {#        年龄#}
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2  col-md-offset-2 control-label">年龄</label>
            <div class="col-sm-4">
                <input type="text" name="age" class="form-control" id="inputPassword3" placeholder="Age">
            </div>
        </div>

        {#        性别#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label">性别</label>

            <label class="radio-inline" style="margin-left: 20px">
                <input type="radio" name="gender" value="1" checked>男
            </label>

            <label class="radio-inline">
                <input type="radio" name="gender" value="0">女
            </label>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10"></div>
        </div>

        {#        按钮#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">添加</button>
                &nbsp<a href="{% url 'staff:staffList' %}?page={{ page }}">
                <button type="button" class="btn btn-success" style="margin-left: 20px">返回</button>
            </a>
            </div>
        </div>
    </form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <script src="{% static 'jquery-3.5.1/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery-1.8.3.js' %}"></script>
    <script src="{% static 'js/code.js' %}"></script>
    <title>Title</title>
    <style>
        #top {
            margin: 0px;
        }
    </style>
</head>
<body>

<!--导航栏-->
<nav class="navbar navbar-default" id="top">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#">
                <span class="glyphicon glyphicon-fire " aria-hidden="true"></span>员工管理</a>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if request.session.username %}
                    <li>
                        <a href="{% url 'staff:staffList' %}">首页 <span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li>
                        <a href="#">首页 <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}

                {% if request.session.username %}
                    <li>
                        <a href="{% url 'staff:add_staff' %}">添加员工<span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            </ul>

            {#        搜索框#}
            {% if request.session.username %}
                <div>
                    <form class="navbar-form navbar-left" action="{% url 'staff:search_staff' %}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="sid" placeholder="ID" style="width: 100px">
                            <input type="text" class="form-control" name="name" placeholder="Name" style="width: 100px">
                            <input type="text" class="form-control" name="age" placeholder="Age" style="width: 100px">
                            <input type="text" class="form-control" name="gender" placeholder="Gender"
                                   style="width: 100px">
                        </div>
                        <button type="submit" class="btn btn-primary">搜索</button>
                    </form>
                </div>
            {% endif %}

            <div style="float: right;margin-top: 10px">
                {% if request.session.username %}
                    {#                    <a class="btn btn-info" href="/blog/content">个人微博</a>#}
                    {#                    <a class="btn btn-success" href="/blog/write">发布微博</a>#}
                    <a class="btn btn-primary" href="#">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"
                                          style="margin:0px">.{{ request.session.username }}
                                    </span>
                    </a>
                    <a class="btn btn-warning" href="{% url 'user_op:logout' %}">退出</a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'user_op:login' %}">登录</a>
                    <a class="btn btn-primary" href="{% url 'user_op:register' %}">注册</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<!-- 容器 -->
<div class="container">
    <div class="row">
        <!-- 内容区 占8格-->
        <div class="col-md-12">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

{#    底栏#}
<div style="float: bottom">
    <nav id="foot" class="navbar navbar-default navbar-fixed-bottom" style="padding-top: 16px">
        <div class="container footbar">
            <div class="text-center text-secondary">Copyright @ LiuBuFan</div>
        </div>
    </nav>
</div>


</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <style type="text/css">
        #canvas {
            border: 1px solid #ccc;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>

    <h1 align="center">登录</h1>
    <hr>

    {% if error == 1 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">用户不存在！</div>
    {% endif %}

    {% if error == 0 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">密码错误！</div>
    {% endif %}

    {% if error == 2 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">验证码错误！</div>
    {% endif %}

    <div style="margin-top: 50px"></div>

    <form class="form-horizontal" action="{% url 'user_op:login' %}" method="POST" enctype="multipart/form-data">
        {#       用户名#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">用户名</label>
            <div class="col-sm-4">
                <input type="text" name="username" class="form-control" id="account" placeholder="Account">
            </div>
        </div>

        {#        密码#}
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2  col-md-offset-2 control-label">密码</label>
            <div class="col-sm-4">
                <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
        </div>

        {#        验证码#}
        <div class="form-group">
            <label for="inputyzm" class="col-sm-2  col-md-offset-2 control-label">
                验证码</label>
            <div class="col-sm-4">
                <input type="text" value="" placeholder="请输入验证码（不区分大小写）" class="form-control" id="inputyzm">
            </div>
            <canvas id="canvas" width="100" height="33px"></canvas>
        </div>

        <div class="form-group">
            <label for="inputyzm" class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <span style="color: red;font-size: 16px" id="span1"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-8"></div>
        </div>

        {#        隐式提交#}
        <input type="hidden" name="yzm" value="0" id="yzm">

        {#        按钮#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <button type="submit" id="toast" class="btn btn-success">登录</button>
                &nbsp<a href="{% url 'user_op:register' %}">
                <button type="button" class="btn btn-success" style="margin-left: 20px">注册</button>
            </a>
            </div>
        </div>
    </form>


    <script>
        $().ready(function () {
            code_draw();
            // 点击后刷新验证码
            $("#canvas").on('click', function () {
                code_draw();
            })

            $("#inputyzm").blur(function () {
                // 将输入的内容转为大写，可通过这步进行大小写验证
                var val = $("#inputyzm").val().toLowerCase();
                // 获取生成验证码值
                var num = $('#canvas').attr('data-code');

                if (val == '') {
                    $('#span1').html('*请输入验证码')
                    $('#toast').attr('disabled',true)
                    $('#yzm').attr('value','0')
                } else if (val == num) {
                    $('#span1').html('')
                    $('#toast').attr('disabled',false)
                    $('#yzm').attr('value','1')
                    draw(show_num);
                } else {
                    $('#span1').html('*验证码有误')
                    $('#toast').attr('disabled',true)
                    $('#yzm').attr('value','0')
                    draw(show_num);
                }
            })
        })
    </script>



{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

    <h1 align="center">注册</h1>
    <hr>

    {% if error == 1 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">密码有误！</div>
    {% endif %}

    {% if error == 0 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">用户名已注册或用户名有误！</div>
    {% endif %}

    <div style="margin-top: 50px"></div>

    <form class="form-horizontal" action="{% url 'user_op:register' %}" method="POST" enctype="multipart/form-data">
        {#       用户名#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">用户名</label>
            <div class="col-sm-4" style="float: left">
                <input type="text" name="username" class="form-control" id="account" placeholder="Account(6~12)">
            </div>
            <div><span style="color: red;float:left;font-size: 16px" id="span1"></span></div>
        </div>

        {#密码#}
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2  col-md-offset-2 control-label">密码</label>
            <div class="col-sm-4" style="float: left">
                <input type="password" name="password" class="form-control" id="inputPassword3"
                       placeholder="Password(6~12)">
            </div>
            <div><span style="color: red;float:left;font-size: 16px" id="span2"></span></div>
        </div>

        {#        确认密码#}
        <div class="form-group">
            <label for="inputPassword2" class="col-sm-2  col-md-offset-2 control-label">确认密码</label>
            <div class="col-sm-4" style="float: left">
                <input type="password" name="password2" class="form-control" id="inputPassword2"
                       placeholder="Confirm Password">
            </div>
            <div><span style="color: red;float:left;font-size: 16px" id="span3"></span></div>
        </div>

        {#        年龄#}
        <div class="form-group">
            <label for="inputage" class="col-sm-2  col-md-offset-2 control-label">年龄</label>
            <div class="col-sm-4" style="float: left">
                <input type="text" name="age" class="form-control" id="inputage"
                       placeholder="Age(1-100)">
            </div>
            <div><span style="color: red;float:left;font-size: 16px" id="span4"></span></div>
        </div>


        {#        性别#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label">性别</label>

            <label class="radio-inline" style="margin-left: 20px">
                <input type="radio" name="gender" value="1" checked>男
            </label>

            <label class="radio-inline">
                <input type="radio" name="gender" value="0">女
            </label>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10"></div>
        </div>

        {#        按钮#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">注册</button>
                &nbsp<a href="{% url 'user_op:login' %}">
                <button type="button" class="btn btn-success" style="margin-left: 20px">返回</button>
            </a>
            </div>
        </div>
    </form>


    <script>
        //当网页加载完成时
        $().ready(function () {
            var account = $('#account')
            var password = $('#inputPassword3')
            var comfirm_pwd = $('#inputPassword2')
            var age = $('#inputage')

            //account失去焦点的时候
            account.blur(function () {
                //获取input值的长度
                if (account.val().length < 6 || account.val().length > 12) {
                    $('#span1').html('*长度不符')
                } else {
                    $('#span1').html('')
                }
            })
            //pwd失去焦点的时候
            password.blur(function () {
                //获取input值的长度
                if (password.val().length < 6 || password.val().length > 12) {
                    $('#span2').html('*长度不符')
                } else {
                    $('#span2').html('')
                }
            })
            //comfirm-pwd失去焦点的时候
            comfirm_pwd.blur(function () {
                //获取input值的长度
                if (comfirm_pwd.val() != password.val()) {
                    $('#span3').html('*两次密码不同')
                } else {
                    $('#span3').html('')
                }
            })
            //age失去焦点的时候
            age.blur(function () {
                //获取input值的长度
                if (age.val().length < 1) {
                    $('#span4').html('*年龄不能为空')
                } else if (age.val()<1 || age.val()>100){
                    $('#span4').html('*请输入正确的年龄')
                } else {
                    $('#span4').html('')
                }
            })

        })


    </script>

{% endblock %}

templates/search_staff.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center">搜索列表</h1>
    <hr>

    {% if error == 0 %}
        <div class="alert alert-danger" role="alert" style="text-align: center">无匹配员工！</div>
    {% endif %}

    <table class="table table-hover" style="font-size: 20px">
        <tr class="info" style="text-align: center">
            <th>ID</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>操作</th>
        </tr>
        {% for staff in page %}
            <tr>
                <td>{{ staff.id }}</td>
                <td><a href="{% url 'staff:staff_info' %}?sid={{ staff.id }}">{{ staff.name }}</a></td>
                <td>{{ staff.age }}</td>
                {% if staff.gender %}
                    <td>男</td>
                {% else %}
                    <td>女</td>
                {% endif %}

                <td>
                    <a href="{% url 'staff:staff_delete' %}?sid={{ staff.id }}">删除</a>
                    &nbsp&nbsp
                    <a href="{% url 'staff:staff_update' %}?sid={{ staff.id }}">修改</a>
                </td>
            </tr>
        {% endfor %}
    </table>


    {#    ----------------------------------分页-------------------#}
    <div align="center" style="margin-bottom: 30px">
        <nav aria-label="Page navigation" class="navbar-sta">
            <ul class="pagination">

                {#前一页#}
                <li>
                    {% if page.has_previous %}
                        <a href="{% url 'staff:search_staff' %}
                        ?sid={{ search_info.id }}&name={{ search_info.name }}&age={{ search_info.age }}
                        &gender={{ search_info.gender }}&page={{ page.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a href="#" aria-label="Previous" style="color: gray">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>
                {#页码显示#}
                {% for x in page_range %}
                    {% if x == page.number %}
                        <li><a href="#" style="color: gray">{{ x }}</a></li>
                    {% else %}
                        <li><a href="{% url 'staff:search_staff' %}
                        ?sid={{ search_info.id }}&name={{ search_info.name }}&age={{ search_info.age }}
                        &gender={{ search_info.gender }}&page={{ x }}">{{ x }}</a></li>
                    {% endif %}
                {% endfor %}

                {#后一页#}
                <li>
                    {% if page.has_next %}
                        <a href="{% url 'staff:search_staff' %}
                        ?sid={{ search_info.id }}&name={{ search_info.name }}&age={{ search_info.age }}
                        &gender={{ search_info.gender }}&page={{ page.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <a href="#" aria-label="Next" style="color: gray">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

templates/staffList.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center">员工列表</h1>
    <hr>

    <table class="table table-hover" style="font-size: 20px">
        <tr class="info" style="text-align: center">
            <th>ID</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>操作</th>
        </tr>
        {% for staff in page %}
            <tr>
                <td>{{ staff.id }}</td>
                <td>
                    <a href="{% url 'staff:staff_info' %}?sid={{ staff.id }}&page={{ page.number }}">{{ staff.name }}</a>
                </td>
                <td>{{ staff.age }}</td>
                {% if staff.gender %}
                    <td>男</td>
                {% else %}
                    <td>女</td>
                {% endif %}

                <td>
                    <a href="{% url 'staff:staff_delete' %}?sid={{ staff.id }}&page={{ page.number }}">删除</a>
                    &nbsp&nbsp
                    <a href="{% url 'staff:staff_update' %}?sid={{ staff.id }}&page={{ page.number }}">修改</a>
                </td>
            </tr>
        {% endfor %}
    </table>


    {#    ----------------------------------分页-------------------#}
    <div align="center" style="margin-bottom: 30px">
        <nav aria-label="Page navigation" class="navbar-sta">
            <ul class="pagination">

                {#前一页#}
                <li>
                    {% if page.has_previous %}
                        <a href="{% url 'staff:staffList' %}?page={{ page.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a href="#" aria-label="Previous" style="color: gray">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>
                {#页码显示#}
                {% for x in page_range %}
                    {% if x == page.number %}
                        <li><a href="#" style="color: black">{{ x }}</a></li>
                    {% else %}
                        <li><a href="{% url 'staff:staffList' %}?page={{ x }}">{{ x }}</a></li>
                    {% endif %}
                {% endfor %}

                {#后一页#}
                <li>
                    {% if page.has_next %}
                        <a href="{% url 'staff:staffList' %}?page={{ page.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <a href="#" aria-label="Next" style="color: gray">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

templates/staff_info.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center">员工个人信息</h1>
    <hr>


    <form class="form-horizontal" style="margin-top: 10px">
        {#        id#}
        <div class="form-group">
            <label for="userid" class="col-sm-2 col-md-offset-2 control-label">ID</label>
            <div class="col-sm-4">
                <input type="text" name="id" class="form-control" id="userid"
                       placeholder="{{ staff.id }}" disabled>
            </div>
        </div>

        {#        名字#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">用户名</label>
            <div class="col-sm-4">
                <input type="text" name="name" class="form-control" id="account"
                       placeholder="{{ staff.name }}" disabled>
            </div>
        </div>

        {#        年龄#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">年龄</label>
            <div class="col-sm-4">
                <input type="text" name="name" class="form-control" id="account"
                       placeholder="{{ staff.age }}" disabled>
            </div>
        </div>

        {#        性别#}
        {% if staff.gender == 1 %}
            <div class="form-group">
                <label for="inputgender1" class="col-sm-2  col-md-offset-2 control-label">性别</label>
                <div class="col-sm-4">
                    <input type="text" name="birthday" class="form-control" id="inputgender1"
                           placeholder="小哥哥" disabled>
                </div>
            </div>
        {% else %}
            <div class="form-group">
                <label for="inputgender2" class="col-sm-2  col-md-offset-2 control-label">性别</label>
                <div class="col-sm-4">
                    <input type="text" name="birthday" class="form-control" id="inputgender2"
                           placeholder="小姐姐" disabled>
                </div>
            </div>
        {% endif %}

        <div class="form-group">
            <div class="col-sm-8"></div>
        </div>

        {#按钮#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <a href="{% url 'staff:staffList' %}?page={{ page }}">
                    <button type="button" class="btn btn-info">返回</button>
                </a>
            </div>
        </div>

    </form>

{% endblock %}

templates/staff_update.html
{% extends 'base.html' %}

{% block content %}
    <h1 align="center">修改员工信息</h1>
    <hr>


    <form class="form-horizontal" action="{% url 'staff:staff_update' %}" method="POST" enctype="multipart/form-data">
        {#       名字#}
        <div class="form-group">
            <label for="account" class="col-sm-2 col-md-offset-2 control-label">名字</label>
            <div class="col-sm-4">
                <input type="text" name="name" class="form-control" id="account"
                      value="{{ staff.name }}" placeholder="{{ staff.name }}">
            </div>
        </div>

        {#        年龄#}
        <div class="form-group">
            <label for="inputPassword2" class="col-sm-2  col-md-offset-2 control-label">年龄</label>
            <div class="col-sm-4">
                <input type="text" name="age" class="form-control" id="inputPassword2"
                       value="{{ staff.age }}" placeholder="{{ staff.age }}">
            </div>
        </div>


        {#        性别#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label">性别</label>
            {% if staff.gender == 1 %}
                <label class="radio-inline" style="margin-left: 20px">
                    <input type="radio" name="gender" value="1" checked>男
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="0">女
                </label>
            {% else %}
                <label class="radio-inline" style="margin-left: 20px">
                    <input type="radio" name="gender" value="1">男
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="0" checked>女
                </label>
            {% endif %}

        </div>

        <div class="form-group">
            <div class="col-sm-8"></div>
        </div>

        {#       隐式提交员工id#}
        <input type="hidden" name="sid" value="{{ sid }}">
        <input type="hidden" name="page" value="{{ page }}">


        {#       按钮#}
        <div class="form-group">
            <label class="col-sm-2  col-md-offset-2 control-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-info">修改</button>
                &nbsp<a href="{% url 'staff:staffList' %}?page={{ page }}">
                <button type="button" class="btn btn-info" style="margin-left: 20px">返回</button>
            </a>
            </div>
        </div>
    </form>

{% endblock %}